### ISSUE TITLE
Finalise integration with ABaCus

### ISSUE THREAD

**Issue by tanhevg** [tanhevg/GpABC.jl#3]

**Comment by FeiHeIC** [comment]
1. Input parameters: default -  the number of accepted parameters in the posterior (or for each population in the ABC-SMC), and threshold values $\varepsilon_t$ (ABC-SMC); optional - prior distribution, summary statistics, distance function.
2. Display the progress of ABC:  accepted number of samples from each Monte-Carlo; remove all the other displays in ABaCus by removing those 6 lines from io.jl file (ask Fei).
3. Outputs: a 'result' data structure (including posterior population (default), distances, weights) and a N-by-N-dimensional scatter-plots (diagonal are the marginal distributions) -- Fei has the code for such a plot.
