### ISSUE TITLE
Version compatibility with KernelDensity.jl

### ISSUE THREAD

**Issue by fkrauer** [tanhevg/GpABC.jl#68]
Hi

I am trying to install GpABC. Unfortunately, there is a version compatibility issue with KernelDensity.jl (GpABC requires 0.5.0-0.5.1), but I have a requirement for 0.6.3 from other packages. What's the best approach to solve this? Thanks

**Comment by tanhevg** [comment]
KernelDensity.jl dependency version bumped in the most recent release of GpABC.jl
